Repository ElmsCollege/elms-college-redesign, pull requests merged in 2021-01, with the labels that each got.

#124 Changing email encoders
  css/library.css
  css/nursing.css
  css/print.css
  page-35268.php
  scss/_mec-calendar.scss
  scss/_utilities.scss
  scss/library.scss
  scss/nursing.scss
  scss/print.scss
  scss/style.scss
  single-personnel.php
  style.css
  webnus/modern-events-calendar-lite/app/skins/list/render.php
  webnus/modern-events-calendar-lite/app/skins/single/default.php
Labels: bug, minor, patch

#125 There is a styling issue with the directory in Firefox where a direct…
  css/directory.css
  scss/directory.scss
Labels: bug, patch

#126 Email encoder hotfix 1
  css/directory.css
  footer-advertising.php
  footer-library.php
  footer.php
  page-1635.php
  scss/directory.scss
  scss/style.scss
  single-personnel.php
  style.css
Labels: bug, patch

#127 Adding a link to the newly created EOP page to make that policy more …
  footer-library.php
  footer.php
  page-1635.php
Labels: minor

#128 Updating curriculum block
  acf-json/group_5e1dfe7b3f1ed.json
  blocks/lazyblock-acf-curriculum-fields/block.php
  blocks/lazyblock-acf-curriculum-fields/editor.php
  css/pure.0.6.0.css
  scss/_curriculum-block.scss
  scss/pure.0.6.0.scss
  scss/style.scss
  style.css
Labels: minor
